# Generated by Django 6.0.4 on 2026-04-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('demand', models.FloatField()),
                ('is_historical', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_type', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=200)),
                ('geopolitical_reasons', models.TextField()),
                ('trend_direction', models.CharField(max_length=20)),
            ],
        ),
    ]
